site_url: https://bblk.pl

backend:
  name: git-gateway
  branch: master

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

media_folder: 'content/uploads'
public_folder: '/uploads'

collections:
  - label: 'Blog post'
    name: 'blog-post'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: '/blog/{{slug}}'
    extension: mdx
    format: frontmatter
    fields:
      - label: 'Template Key'
        name: templateKey
        widget: hidden
        default: blog-post

      - label: Title
        name: title
        widget: string

      - label: 'Publish Date'
        name: date
        widget: datetime
        date_format: 'DD MMMM, YYYY'
        time_format: 'HH:mm'

      - label: Description
        name: description
        widget: text

      - label: 'Featured Image'
        name: featuredImage
        widget: image
        required: false
        fields:
          - label: 'Caption'
            name: 'caption'
            widget: string
            required: false

      - label: Body
        name: body
        widget: markdown

      - label: Tags
        name: tags
        widget: list
        required: false
        allow_add: true

  - label: 'Demo'
    name: 'demo'
    folder: 'content/demos'
    create: true
    slug: '{{slug}}'
    preview_path: '/demos/{{slug}}'
    extension: mdx
    format: frontmatter
    fields:
      - label: 'Template Key'
        name: templateKey
        widget: hidden
        default: demo

      - label: Title
        name: title
        widget: string

      - label: 'Publish Date'
        name: date
        widget: datetime
        date_format: 'DD MMMM, YYYY'
        time_format: 'HH:mm'

      - label: 'Featured Image'
        name: featuredImage
        widget: image
        required: false

      - label: Description
        name: description
        widget: text

      - label: 'Source URL'
        name: sourceURL
        widget: string
        required: false

      - label: 'Live demo URL'
        name: liveDemoURL
        widget: string
        required: false

      - label: Tags
        name: tags
        widget: list
        required: false
        allow_add: true
